## CHANGE this to the name of your plugin.
name: ExLimus

## CHANGE this to your username.
author: TerslenK

## CHANGE this to a meaninful but short description of your plugin.
description: 2 words, "Ex Nihilio"

## CHANGE this to the path of the class that extends JavaPlugin.
main: io.github.terslenk.exlimus.ExLimus

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/TerslenK/ExLimus

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.17

## This is required and marks Slimefun as a plugin dependency.
depend:
- Slimefun